permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown
highlighter: pygments

# author information
author:
  name: yxjxx
  email: mynameisyxjxx@gmail.com
  link: http://blog.yxjxx.com
  weibo: http://weibo.com/u/2178068823
  github: http://github.com/yxjxx

# site information
title: yxjxx's blog
description: yxjxx's blog
url: http://blog.yxjxx.com
rss_url: /pages/atom.xml
commentsystem:  duoshuo

# gavatar and favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico

# google analytics config
ga:
  id: UA-44052834-3
  url: yxjxx.com

# disqus config
disqus:
  shortname: yxj

# topic config, auto active a tag
active: 技术

# 首页除了最新文章外显示分类
cates:
  - Python

# chinese localization
locals:
  tags: 标签
  about: 关于
  newest: 最新文章

#Custom vars
icon: /assets/images/icon.png
cover: /assets/images/cover.jpg

social:
    - icon: twitter
      url:  https://twitter.com/yxjxx
      desc: Follow me on twitter

    - icon: github
      url:  https://github.com/yxjxx
      desc: Fork me on github

    - icon: feed
      url:  http://blog.yxjxx.com/atom.xml
      desc: Subcribe to my feed

menu:
    - title: Home
      url:   /

    - title: About
      url:   /about

copyright:
    author: yxjxx
    url:    http://blog.yxjxx.com
    type_title: Some rights reserved
    type_url:   http://creativecommons.org/licenses/by-nc/2.5
    theme:      Thinny
    theme_url:  https://github.com/camporez/Thinny

comments:
    provider: duoshuo
    duoshuo :
        short_name: yxjxx
